//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.Label L1;
        protected System.Web.UI.WebControls.Label L2;
        protected System.Web.UI.WebControls.Label L3;
        protected System.Web.UI.WebControls.Label L4;
        protected System.Web.UI.WebControls.Label L5;
        protected System.Web.UI.WebControls.Label L6;
        protected System.Web.UI.WebControls.Label L7;
        protected System.Web.UI.WebControls.Label L8;
        protected System.Web.UI.WebControls.Label L9;
        protected System.Web.UI.WebControls.Label L10;
        protected System.Web.UI.WebControls.Label L11;
        protected System.Web.UI.WebControls.Label L12;
        protected System.Web.UI.WebControls.Label L13;
        protected System.Web.UI.WebControls.Label L14;
        protected System.Web.UI.WebControls.Label L15;

		
		protected System.Web.UI.WebControls.Button button1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form2;
		
		protected System.Web.UI.WebControls.Button button2;
	}
}
