//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company
{


    public partial class UploadNew
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.TextBox type_id;
        protected global::System.Web.UI.WebControls.TextBox subcategory_name;
        protected global::System.Web.UI.WebControls.TextBox category_id;
        protected global::System.Web.UI.WebControls.TextBox link;
        protected global::System.Web.UI.WebControls.Button Button1;
        protected global::System.Web.UI.WebControls.Button Button2;
        protected global::System.Web.UI.WebControls.GridView GridView1;
    }
}
